### ISSUE TITLE
[Question] sorry this is not a bug just a question

### ISSUE THREAD

**Issue by azkadev** [jpjonte/NESd#59]
is it possible for flutter and dart native to create emulators other than nes?
like ps2 / ps3 / ps1 / whatever emulator

**Comment by jpjonte** [comment]
Hi @azkadev, sorry for the late reply. For some reason I didn't get a notification about your question.

It's definitely possible to create other emulators. I'm thinking of adding support for other retro platforms once NES support is more mature (like Sega Master System, GameBoy, SNES, etc.).

With more modern platforms like PS3 I think performance will be an issue. It's a difficult system to emulate.

PS1 and other 3D consoles might be possible, but I haven't looked much into the 3D capabilities of Flutter, so I can't say for sure.
